version: '2'
services:
  web:
    volumes:
      - ./{{ project_name }}-web/:/opt/{{ project_name }}/{{ project_name }}-web/
    environment:
        RUN_MODE: DEVELOPMENT
    command: bash web.sh

  testing:
    volumes:
      - ./testing/:/opt/{{ project_name }}/{{ project_name }}-testing/
      # to be able to automate test for veryfing if docs are reloaded after changing docs' source files
      - ./docs/:/opt/{{ project_name }}/{{ project_name }}-testing/docs

  https:
    volumes_from:
      - web
