version: '2'
services:
  web:
    build:
      context: ./{{ project_name }}-web
      dockerfile: Dockerfile-web.docker
    restart: always
    command: bash web-production.sh

  db:
    restart: always

  https:
    restart: always
